project:
  type: website

website:
  title: "0x15"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/johnrieth
      - icon: twitter
        href: https://twitter.com/0x15__
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

